asignments/urls.py
from django.urls import path
from . import views

# defined the urls for my app here
urlpatterns = [
    # url for homepage
    path('',views.index,name = 'index'),
    # url for create page
    path('create/' ,views.create, name = 'create'),
    # url for update page which takes as an argument the id of the model you want to edit
    path(r'^update/(?P<model_id>\d+)/$',views.update, name = 'update'),
]

assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('asignments.urls','assignments'),namespace='assignments')),
]

asignments/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.dispatch import receiver
from .signalUtils import UpdateSignal
from .encrypt import encryptfile
from django.db.models.signals import post_save

# Creating a QuerySet to handel update of content
class MyModelQueryset(QuerySet):

    # defining update function to send signals on update of content
    def update(self, **kwargs):
        model_id = self[0].id
        m1 = MyModel.objects.get(id = model_id)
        # checking for filefield
        if 'myfile' in kwargs.keys():
            print('inside')
            kwargs['myencryption'] = encryptfile(kwargs['myfile'])
        # sending update signal
        UpdateSignal.send(MyModel, olderModel = m1, changedArguments = kwargs)
        print(kwargs)
        return super().update(**kwargs)

# Create your models here.
class MyModel(models.Model):

    # assigning MyModelQuerySet to MyModel
    objects = MyModelQueryset.as_manager()

    # defining the model
    myfilename = models.CharField(max_length = 200)
    myfile = models.FileField(upload_to='asignments/uploads/')
    myencryption = models.CharField(max_length = 1500)

    # defining string representation of model class
    def __str__(self):
        return self.myfilename



# creating a reciever function for UpdateSignal to store the message in output.txt
@receiver(UpdateSignal,sender = MyModel)
def onUpdateCalled(sender,**kwargs):
    # making the output
    output = "The model " + kwargs['olderModel'].myfilename + " is updated."
    
    for key in kwargs['changedArguments'].keys():
        if key == 'myfilename':
            output = output + ' The older value of myfilename is ' + kwargs['olderModel'].myfilename + " and new value is " + kwargs['changedArguments'][key]
        if key == 'myencryption':
            output = output + ' The older value of myencryption is ' + kwargs['olderModel'].myencryption + " and new value is " + kwargs['changedArguments'][key]
        if key == 'myfile':
            output = output + ' The older value of myfile is ' + kwargs['olderModel'].myfile.name + " and new value is " + kwargs['changedArguments'][key].name
    
    output = output + '\n'
    
    # saving to file
    f = open('output.txt','a')
    f.write(output)
    f.close()

# reciever function for post_save signal 
@receiver(post_save,sender = MyModel)
def onSaveCalled(sender,**kwargs):
    # making the output
    output = ""

    output = output + "The model " + kwargs['instance'].myfilename + " is created with fields myfilename = " + kwargs['instance'].myfilename + " myencryption = " + kwargs['instance'].myencryption +" and myfile = "+ kwargs['instance'].myfile.name
    output = output + "\n"

    # saving output to file
    f = open('output.txt','a')
    f.write(output)
    f.close()

asignments/forms.py
from django import forms

# created a form for MyModel 
class MyModelForm(forms.Form):
    myfilename = forms.CharField(max_length = 200)
    myfile = forms.FileField()

asignments/views.py
from django.shortcuts import render
from .models import MyModel
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import MyModelForm
from django.core.files import File
from .encrypt import encrypt
import os
# Create your views here.

# index view 
# this view is making the homepage of the app
def index(request):
    # creating a list of models ordered by filename and sending them to template
    mymodels = MyModel.objects.order_by('myfilename')
    context = {'mymodels':mymodels}
    return render(request,'asignments/index.html',context)

# create view
# this view is used for making new entries in the database
def create(request):

    if(request.method == 'POST'):
        
        # using model form to handel the file upload
        form = MyModelForm(request.POST , request.FILES)
        if form.is_valid:
            
            #creating a model instance to handel the encryption process before creating the entry
            m1 = MyModel()

            # the handle_upload_file function is used to handel the file uploaded and the encryption of file data
            m1.myencryption = handle_uploaded_file(request.POST['myfilename'],request.FILES['myfile'])
            
            m1.myfilename = request.POST['myfilename']
            m1.myfile = File(open('asignments/uploads/'+ request.POST['myfilename'],'r'))
            m1.save()
            os.remove('asignments/uploads/' + request.POST['myfilename'])
            
            # redirecting to homepage
            return HttpResponseRedirect(reverse('assignments:index'))
    
    # rendering the create page
    return render(request,'asignments/create.html')

# definig a view to update the content of the file
# this function uses html form to get content of updated file
def update(request, model_id):
    # getting the model we want to update content of
    model = MyModel.objects.get(id = model_id)
    
    data = ""
    with open(model.myfile.path,'r') as f:
        data = data + f.read()

    if request.method == 'POST':
        # updating the content of the file
        with open(model.myfile.path,'w') as f:
            f.write(request.POST["content"])

        # updating the content of the file into the database
        # the overriden update function will take care of the encryption value related to file
        MyModel.objects.filter(id = model_id).update(myfile = model.myfile)

        # redirecting to the homepage
        return HttpResponseRedirect(reverse('assignments:index'))

    # sending the initial data of the file as well as the model instance to template to edit the data of file    
    context = {'data':data,'model':model}

    # rendering the html page
    return render(request,'asignments/update.html',context)
        
# function to handel upload of the file
# n is the name of the file
# f is the request.FILES 
def handle_uploaded_file(n,f):

    # saving the data bytes of the file into the file 
    with open('asignments/uploads/' + n, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

    # reading the data to get encrypted value of the file content
    with open('asignments/uploads/' + n, 'r') as destination:
        data = destination.read()

    # returning the encrypted data
    return encrypt(data)

asignments/templates/asignments/create.html
<!DOCTYPE html>
 <!-- this is the create page -->
<html>
    <head>
        <title>
            create
        </title>
    </head>
    <body>
         <!-- form to create a model in database> -->
        <form action="{% url 'assignments:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- input field for filename -->
            <input type="text" name="myfilename" placeholder = "filename" required>
            <br>
            <!-- input field for file -->
            <input type="file" name="myfile" required>
            <br>
             <!-- submit button -->
            <input type="submit">
        </form>
    </body>
</html>

asignments/templates/asignments/index.html
<!DOCTYPE html>
<!-- the home page of the app -->
<html>
    <head>
        <title>homepage</title>
    </head>
    <body>
         <!-- link to create page -->
        <a href="{% url 'assignments:create' %}">create</a>
        <br>
         <!-- list of all the models that you can update -->
        <ul>
            {% for item in mymodels %}
            <li><a href="{% url 'assignments:update' item.id %}">{{item}}</a></li>
            {% endfor %}
        </ul>

    </body>
</html>

asignments/templates/asignments/update.html
<!DOCTYPE html>
<!-- this is the page to update the content of the file -->
<html>
    <head>
        <title>
            update
        </title>
    </head>
    <body>
        <!-- this form is made so that user can edit the content of the file
        the content of the file will be displayed in the textarea and user can edit it easily -->
        <form action="{% url 'assignments:update' model.id %}" method="POST">
            {% csrf_token %}
            <textarea name="content" cols="30" rows="10" >{{data}}</textarea>
            <input type="submit">
        </form>
    </body>
</html>